version: '3.7'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  client:
    hostname: localhost
    container_name: angular-container
    build: 
      context: client
      dockerfile: Dockerfile
    ports: 
      - 4200:4200
